### ISSUE TITLE
Add Kotlin SDK to list of SDKs

### ISSUE THREAD

**Issue by ire-and-curses** [stellar/developers#119]
Add here, on both sidebar and main body: https://www.stellar.org/developers/reference/

It took me a little while to find it earlier today (https://github.com/Inbot/inbot-stellar-kotlin-wrapper), it's active, and it's probably preferable to Android devs over our vanilla Java SDK.

**Comment by rice2000** [comment]
Closing this since Kotlin SDK is on ice.
