### ISSUE TITLE
Sort sidebar alphabetically

### ISSUE THREAD

**Issue by irisli** [stellar/developers#12]
Globs don't ensure that the result is sorted alphabetically. Some things are sorted alphabetically but is grouped with other files of the same type.

Here is an example:
![image](https://cloud.githubusercontent.com/assets/5728307/10252754/6bd28daa-68ee-11e5-88b1-d42ed525af00.png)

In this example, pdf files and html files are grouped separately.

**Comment by jedmccaleb** [comment]
I would be fine with it sorted like: 
admin
commands
testnet
core data flow

**Comment by bartekn** [comment]
Seems to be resolved. Closing.
