### ISSUE TITLE
Formatting issue on the main website.

### ISSUE THREAD

**Issue by kitsunde** [stellar/developers#87]
There doesn't seem to be a repo for the main website, so I'm leaving this here.

On https://www.stellar.org/how-it-works/stellar-basics/ bottom right corner seem to suggest something was intended to be commented out:

<img width="1228" alt="screenshot 2017-05-07 20 58 12" src="https://cloud.githubusercontent.com/assets/48965/25781142/fadcd524-3367-11e7-892b-535584ba9e3d.png">

**Comment by bartekn** [comment]
Thanks!
