### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by bartekn** [stellar/developers#89]
It's currently impossible to build a project, probably broken since: https://github.com/stellar/developers/pull/88.

```
[12:01:41] 'build' errored after 650 ms
[12:01:41] Error: ENOENT: no such file or directory, stat '/Users/bartek/developers/src/horizon'
    at Error (native)
```

Looks like `src/horizon` symlink destination doesn't exist:
```
horizon -> ../repos/go/services/horizon/docs
```

I would fix this but I'm not sure what was a decision around horizon docs when moving it to monorepo (https://github.com/stellar/go/pull/93).

**Comment by nikhilsaraf** [comment]
We moved horizon again from `services/horizon` to `services/horizon/internal` so will update this right now too.

**Comment by bartekn** [comment]
This is the latest build: https://www-stg.stellar.org/developers/reference/

Menu items are missing:
![screen shot 2017-10-19 at 21 47 18](https://user-images.githubusercontent.com/464938/31790851-24b76450-b517-11e7-8eac-5a70a546b5d3.png)

Please ensure it's working correctly on your machine.
