### ISSUE TITLE
Babel failing on `babel-register` requirement

### ISSUE THREAD

**Issue by altryne** [stellar/developers#94]
I wanted to contribute to the developer site. 
Followed the steps, installed node modules. 
And then when running `gulp watch serve` it fails because of an unmet dependency : 

<img width="742" alt="image" src="https://user-images.githubusercontent.com/463317/34529064-a1e8bcac-f05f-11e7-9739-40bb3a702999.png">

**Comment by bartekn** [comment]
Are you sure you've installed dependencies (`npm install`)? I'll reopen if you confirm you did.
